# Generated by Django 2.1.8 on 2019-05-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190522_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
