# Generated by Django 2.1.8 on 2019-05-22 20:30

from django.db import migrations, models
import noticeboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=1024)),
                ('notice_pdf_file', models.FileField(upload_to='noticeFiles/', validators=[noticeboard.models.fileValidation_extension])),
            ],
        ),
    ]
