# Generated by Django 2.1.8 on 2020-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190524_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=300)),
                ('Message', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
