# Generated by Django 2.1.8 on 2020-06-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_information',
            old_name='Message',
            new_name='message',
        ),
    ]
