# Generated by Django 2.2.1 on 2019-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('teacher_photo', models.ImageField(blank=True, upload_to='imageFiles')),
                ('facebook_profile', models.CharField(blank=True, max_length=1024)),
                ('instagram_profile', models.CharField(blank=True, max_length=1024)),
                ('twitter_profile', models.CharField(blank=True, max_length=1024)),
                ('googlePlus_profile', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
