# Generated by Django 2.1.8 on 2020-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_auto_20190524_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_materials',
            name='belongs_to',
            field=models.CharField(choices=[('Science', 'SCINECE'), ('English', 'ENGLISH'), ('Commerce', 'COMMERCE'), ('Arts', 'ARTS'), ('All Subject', 'ALL SUBJECT')], default='Science', max_length=20),
        ),
    ]
