# Generated by Django 2.2.1 on 2019-05-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='locatoin',
            new_name='location',
        ),
    ]
