# Generated by Django 2.2.1 on 2019-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200)),
                ('date', models.DateField()),
                ('locatoin', models.CharField(max_length=1200)),
                ('short_description', models.TextField()),
                ('title_image', models.ImageField(blank=True, upload_to='imageFiles')),
                ('youtube_vide_link', models.CharField(blank=True, max_length=1200)),
            ],
        ),
    ]
